System_Sport/urls.py
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.http import JsonResponse
from django.urls import path
from django.urls import include
from myapp import views
from myapp.models import Player

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.default_page, name='default_page'),
    path('home/', views.home, name='home'),
    path('signup/', views.signup, name='signup'),
    path('logout/', views.signout, name='logout'),
    path('signin/', views.signin, name='signin'),
    path('competitions/', views.competition_list, name='competitions'),
    path('competitions/<int:id>/', views.competition_detail, name='competition_detail'),
    path('competitions/competitions_detail<int:id_competition>/new_team/', views.new_team, name='new_team'),
    path('competitions/<int:id_competition>/inscription_player/<int:id_team>/new_player/', views.new_player,
         name='new_player'),
    path('competitions/<int:id_competition>/inscription_player/<int:id_team>/', views.inscription_team,
         name='inscription_team'),

    path('new_sport/', views.new_sport, name='new_sport'),
    path('teams/', views.team_list, name='teams'),
    path('teams/<int:id>/', views.teams_detail, name='teams_detail'),

    path('competitions/<int:id_competition>/seasons/', views.competition_seasons,
         name='competition_seasons'),

    path('competitions/<int:id_competition>/seasons/<int:id_season>/new_stadium/', login_required(views.new_stadium),
         name='new_stadium'),

    path('competitions/<int:id_competition>/seasons/<int:id_season>/', views.season_teams,
         name='season_teams'),

    path('competitions/<int:id_competition>/seasons/<int:id_season>/sortear_grupos/', views.sortear_grupos,
         name='sortear_grupos'),
    path('competitions/<int:id_competition>/seasons/<int:id_season>/deshacer_grupos/', views.undo_group_assignment,
         name='undo_group_assignment'),

    path('competitions/<int:id_competition>/seasons/<int:id_season>/match_season', login_required(views.match_season),
         name='match_season'),
    #    path('competitions/<int:id_competition>/seasons/<int:id_season>/match_season/add_game/<int:id_group>',
    #        login_required(views.add_game), name='add_game'),

    path('competitions/<int:id_competition>/seasons/<int:id_season>/match_season/<int:id_game>/match_detail/',
         login_required(views.match_detail), name='match_detail'),

    path('competitions/<int:id_competition>/seasons/<int:id_season>/generate_time', login_required(views.generate_time),
         name='generate_time'),

    path('competitions/<int:id_competition>/seasons/<int:id_season>/generate_time/add_availability/<int:id_location>',
         login_required(views.agregar_disponibilidad), name='add_availability'),
    path('competitions/<int:id_competition>/seasons/<int:id_season>/generate_time/add_availability/delete_availability',
         login_required(views.delete_availability), name='delete_availability'),
    path('competitions/<int:id_competition>/seasons/<int:id_season>/generate_time/generate_calendar',
         login_required(views.generate_calendar), name='generate_calendar'),

    path('update_game/<int:game_id>', login_required(views.update_game), name='update_game'),
    path('delete_selected_games/', views.delete_selected_games, name='delete_selected_games'),
    path('competitions/<int:id_competition>/seasons/<int:id_season>/delete_season', login_required(views.delete_season),
         name='delete_season'),
    path('search_teams/', views.search_teams, name='search_teams'),
    path('add_team_to_competition/<int:competition_id>/<int:team_id>/', views.add_team_to_competition,
         name='add_team_to_competition'),
    path('generate_test_teams/<int:competition_id>/<int:num_teams>/', views.generate_test_teams,
         name='generate_test_teams'),
    path('toggle_competition/<int:competition_id>/', views.toggle_competition, name='toggle_competition'),

    path('players', views.player_list, name='players'),
    path('player/<int:id>/', views.player_detail, name='player_detail'),
    path('games/', views.game_list, name='game_list'),
    path('game/<int:id>/', views.game_detail, name='game_detail'),
    path('standings/', views.standings_table, name='standings_table'),
    path('edit_player/<int:id>/', views.edit_player, name='edit_player'),
    path('new_competition/', views.new_competition, name='new_competition'),

    path('player_list/', views.player_list, name='player_list'),

    path('accounts/', include('allauth.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myapp/models.py
import random

from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.db import models
from enum import Enum

# Create your models here.
import enum

from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver


# Create your models here.


class Sport(models.Model):
    name = models.CharField(max_length=50)
    image = models.ImageField(upload_to='sport_images/', blank=True, null=True)
    TYPE_SPORT = (
        ('I', 'Individual'),
        ('T', 'Team'),
    )
    type_sport = models.CharField(max_length=1, choices=TYPE_SPORT, blank=True, default='T')

    def __str__(self):
        return self.name


class State(models.TextChoices):
    FINALLY = 'Finally'
    NOT_PLAYED = 'Not played'
    SUSPENDED = 'Suspended'
    CANCELLED = 'Cancelled'
    POSTPONED = 'Postponed'


class Competition(models.Model):
    name = models.CharField(max_length=50, blank=True)
    sport = models.ForeignKey(Sport, on_delete=models.CASCADE)  # Cambio en esta línea
    genre = models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('MF', 'Mixed')], max_length=2, null=True)
    COMPETITION_TYPES = (
        ('L', 'League'),
        ('T', 'Tournament'),
        ('P', 'Playoff'),
        ('F', 'Friendly'),
        ('GS', 'Group Stage'),
        ('O', 'Other')
    )
    type_competition = models.CharField(max_length=2, choices=COMPETITION_TYPES, default='O')
    is_active = models.BooleanField(default=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, related_name='competitions')

    def __str__(self):
        return self.name


class Season(models.Model):
    name = models.CharField(max_length=50)
    date_start = models.DateField(null=True)
    date_end = models.DateField(blank=True, null=True)
    competition = models.ForeignKey(Competition, on_delete=models.CASCADE, related_name='seasons', null=True)
    number_grups = models.IntegerField(default=0)

    def __str__(self):
        return self.name

    def assign_teams_to_groups(self):
        # Obtener los equipos inscritos en esta competencia y temporada
        teams_competition = Team.objects.filter(competition=self.competition)
        teams_season = self.teams.all()  # Obtener los equipos inscritos en esta temporada

        # Combinar los equipos de la competencia y los equipos de la temporada
        all_teams = list(teams_competition) + list(teams_season)
        random.shuffle(all_teams)  # Mezclar aleatoriamente los equipos

        # Obtener los grupos de esta temporada
        groups = self.groups.all()

        # Limpiar los equipos de los grupos antes de asignar nuevos equipos
        for group in groups:
            group.teams.clear()

        # Asignar los equipos a los grupos
        for index, team in enumerate(all_teams):
            group_index = index % self.number_grups  # Asignar equipos de manera circular a los grupos
            groups[group_index].teams.add(team)

    def undo_assign_teams_to_groups(self):
        groups = self.groups.all()

        for group in groups:
            group.teams.clear()

    def get_teams_per_group(self):
        teams_per_group = {}
        groups = self.groups.all()

        for group in groups:
            teams_count = group.teams.count()
            teams_per_group[group] = teams_count

        return teams_per_group


class Group(models.Model):
    letter = models.CharField(max_length=40)
    season = models.ForeignKey(Season, on_delete=models.CASCADE, related_name='groups', null=True)

    def __str__(self):
        return self.letter


class Team(models.Model):
    name = models.CharField(max_length=50)
    city = models.CharField(max_length=50, blank=True)
    country = models.CharField(max_length=50, blank=True)
    image = models.ImageField(upload_to='team_images/', blank=True, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, related_name='teams')
    competition = models.ManyToManyField(Competition, through='Inscription', related_name='teams')
    groups = models.ManyToManyField(Group, related_name='teams', blank=True)
    seasons = models.ManyToManyField(Season, through='TeamSeasonInscription', related_name='teams')

    def __str__(self):
        return self.name


class Inscription(models.Model):
    team = models.ForeignKey(Team, on_delete=models.CASCADE)
    competition = models.ForeignKey(Competition, on_delete=models.CASCADE, related_name='inscriptions', null=True)

    def __str__(self):
        return self.team.name + ' - ' + self.competition.name


class TeamSeasonInscription(models.Model):
    team = models.ForeignKey(Team, on_delete=models.CASCADE)
    season = models.ForeignKey(Season, on_delete=models.CASCADE)

    def __str__(self):
        return self.team.name + ' - ' + self.season.name


class Location(models.Model):
    name = models.CharField(max_length=50)
    number_seats = models.IntegerField(default=0)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, related_name='stadiums')
    addres = models.CharField(max_length=200)
    geolocation = models.CharField(max_length=200, blank=True)

    def __str__(self):
        return self.name


class Phase(Enum):
    GROUP = 'Group'
    EIGHTH_FINALS = 'Eighth Finals'
    QUARTER_FINALS = 'Quarter Finals'
    SEMI_FINALS = 'Semi Finals'
    FINAL = 'Final'


class Game(models.Model):
    date = models.DateField()
    hour = models.TimeField(default='00:00:00')
    team_local = models.ForeignKey(Team, on_delete=models.SET_NULL, null=True, related_name='teamLocal')
    team_visitor = models.ForeignKey(Team, on_delete=models.SET_NULL, null=True, related_name='teamVisitor')
    state = models.CharField(max_length=50, choices=[(tag.name, tag.value) for tag in State],
                             default=State.NOT_PLAYED.value)
    winner = models.ForeignKey(Team, on_delete=models.SET_NULL, null=True, blank=True, related_name='winning_games')
    loser = models.ForeignKey(Team, on_delete=models.SET_NULL, null=True, blank=True, related_name='losing_games')
    location = models.ForeignKey(Location, on_delete=models.SET_NULL, null=True, blank=True)
    phase = models.CharField(max_length=50, choices=[(tag.name, tag.value) for tag in Phase], default=Phase.GROUP.value)
    season = models.ForeignKey(Season, on_delete=models.CASCADE, null=True, related_name='games')
    team_local_goals = models.IntegerField(default=0)
    team_visitor_goals = models.IntegerField(default=0)

    def __str__(self):
        return self.team_local.name + ' vs ' + self.team_visitor.name

    def get_result(self):
        if self.score:
            return self.score.result
        return "Not played"


class Score(models.Model):
    result = models.CharField(max_length=50)
    game = models.OneToOneField(Game, on_delete=models.CASCADE, null=True)


class Player(models.Model):
    name = models.CharField(max_length=50)
    number_player = models.IntegerField()
    position = models.CharField(max_length=50)
    image = models.ImageField(upload_to='player_images/', blank=True, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, related_name='players')

    def __str__(self):
        return self.name


class PlayerTeamSeason(models.Model):
    player = models.ForeignKey(Player, on_delete=models.CASCADE)
    team = models.ForeignKey(Team, on_delete=models.CASCADE)

    def __str__(self):
        return self.player.name + ' - ' + self.team.name


class Availability(models.Model):
    DAYS_CHOICES = (
        ('Lunes', 'Lunes'),
        ('Martes', 'Martes'),
        ('Miercoles', 'Miércoles'),
        ('Jueves', 'Jueves'),
        ('Viernes', 'Viernes'),
        ('Sabado', 'Sábado'),
        ('Domingo', 'Domingo'),
    )
    days_available = models.CharField(max_length=50, choices=DAYS_CHOICES, default='Lunes')
    opening_time = models.TimeField(default='00:00:00')
    closing_time = models.TimeField(blank=True, default='00:00:00')
    location = models.ForeignKey(Location, on_delete=models.CASCADE, related_name='availabilities')
    date = models.DateField(blank=True, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, related_name='availabilities')

    def __str__(self):
        return self.location.name + ' - ' + self.days_available


# Función para crear automáticamente los grupos cuando se crea una temporada
@receiver(post_save, sender=Season)
def create_groups_for_season(sender, instance, created, **kwargs):
    if created and instance.number_grups:
        for i in range(instance.number_grups):
            Group.objects.create(letter=f"Grupo {i + 1}", season=instance)

myapp/templates/competitions.html
{% extends 'base.html' %}

{% block content %}

    
    <div class="container mt-5">
        <h1 class="mb-4">Competitions List</h1>

        <div class="d-flex justify-content-end mb-3">
            <a class="btn btn-primary" href="{% url 'new_competition' %}">Crear Competencia</a>
        </div>

        <div class="row">
            {% for competition in competitions %}
                <div class="col-md-6 mb-4">
                    <div class="card bg-dark text-light">
                        <div class="card-body">
                            <h2 class="card-title"><a
                                    href="{% url 'competition_detail' competition.id %}">{{ competition.name }}</a></h2>
                            <p class="card-text text-right">{{ competition.is_active }}</p>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>

{% endblock %}

myapp/templates/generate_time.html
{% extends 'base.html' %}
{% block content %}

    {% load static %}
    {{ form.media }}


    <div class="container">
        <a class="" href="{% url 'match_season' competition.id season.id %}">Ir a lista de partidos</a>


        <div class="row">
            <div class="col">
                <a class="btn btn-primary mt-3" href="{% url 'new_stadium' competition.id season.id %}">Agregar
                    Instalación</a>
            </div>
            <div class="col-md-2 d-flex">
                <a class="btn btn-danger mt-3" href="{% url 'delete_availability' competition.id season.id %}">Limpiar
                    Disponibilidad</a>
            </div>
        </div>


        <div class="card mt-3">
            <div class="card-header">
                Instalaciones y Horarios
            </div>
            <ul class="list-group list-group-flush">
                {% for location in locations %}
                    <li class="list-group-item">
                        <div class="row align-items-center">
                            <div class="col mx-5">
                                <strong class="text-center">{{ location.name }}</strong>
                            </div>
                            <div class="col-md-7 d-flex justify-content-center">
                                {% for availability in availability_data.items %}
                                    {% if location.id == availability.0 %}
                                        {% for avail in availability.1 %}
                                            <div class="card mb-3 mx-3" style="max-width: 15rem;">
                                                <div class="card-body">
                                                    <h5 class="card-title">{{ avail.days_available }}</h5>
                                                    <p class="card-text">
                                                        <i class="fas fa-clock"></i> {{ avail.opening_time }}
                                                        - {{ avail.closing_time }}<br>
                                                        <i class="far fa-calendar-alt"></i> {{ avail.date }}
                                                    </p>
                                                </div>
                                            </div>
                                        {% endfor %}
                                    {% endif %}
                                {% endfor %}
                            </div>

                            <div class="col-md-3 d-flex justify-content-center">
                                <button type="button" class="btn btn-primary" data-toggle="modal"
                                        data-target="#modal{{ location.id }}">Agregar Disponibilidad
                                </button>
                            </div>
                            <!-- Modal -->
                            <div class="modal fade" id="modal{{ location.id }}" tabindex="-1"
                                 aria-labelledby="modal{{ location.id }}" aria-hidden="true">
                                <div class="modal-dialog modal-lg modal-dialog-centered">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="modal{{ location.id }}">Añadir
                                                Disponibilidad</h5>
                                            <button type="button" class="btn-close" data-bs-dismiss="modal"
                                                    aria-label="Close"></button>
                                        </div>
                                        <div class="modal-body">
                                            <form method="post"
                                                  action="{% url 'add_availability' competition.id season.id location.id %}">
                                                {% csrf_token %}
                                                <div class=" form-group">
                                                    <label for="{{ form.days_available.id_for_label }}">Días
                                                        Disponibles:</label><br>
                                                    {% for check in form.days_available %}
                                                        <div class="form-check form-check-inline">
                                                            {{ check.tag }}
                                                            <label class="form-check-label"
                                                                   for="{{ check.id_for_label }}">{{ check.choice_label }}</label>
                                                        </div>
                                                    {% endfor %}
                                                </div>
                                                <div class="row">
                                                    <div class="col-md-6">
                                                        <div class="mt-3">
                                                            <label for="{{ form.opening_time.id_for_label }}">Hora
                                                                de Apertura:</label>
                                                            {{ form.opening_time }}
                                                        </div>
                                                    </div>
                                                    <div class="col-md-6">
                                                        <div class="mt-3">
                                                            <label for="{{ form.closing_time.id_for_label }}">Hora
                                                                de Cierre:</label>
                                                            {{ form.closing_time }}
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="mt-3">
                                                    <label for="{{ form.date.id_for_label }}">Fecha:</label>
                                                    {{ form.date }}
                                                </div>
                                                <button type="submit" class="btn btn-primary mt-3">Guardar</button>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </li>
                {% endfor %}
            </ul>


        </div>

        <section class="mt-5">
            <div class="row">
                <div class="col">
                </div>
                <div class="col-md-2 d-flex">
                    <a class="btn btn-secondary mt-3" href="{% url 'generate_calendar' competition.id season.id %}">Generar
                        Calendario</a>
                </div>
            </div>
        </section>
    </div>



{% endblock %}

myapp/templates/inscription_team.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

    <div class="row">
        <div class="col">
            <a class="" href="{% url 'competition_detail' competition.id %}"><img
                    src="{% static 'img/back.png' %}"
                    alt=""></a>
        </div>
    </div>
    <div class="card mb-3 mt-3">
        <img src="{% static 'img/bannerPlaceholder.png' %}" class="card-img-top" alt="...">
        <div class="card-body">
            <h5 class="card-title">{{ team.name }}</h5>
            <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional
                content. This content is a little bit longer.</p>
            <p class="card-text"><small class="text-body-secondary">Last updated 3 mins ago</small></p>
        </div>
    </div>

    <a href="{% url 'new_player' competition.id team.id %}">Agregar Jugador</a>








    <div class="mt-5 container-">

        <div class="row">
            <div class="col-md-10 mx-auto">
                <div class="d-flex justify-content-end ">
                    <form class="d-none d-sm-inline-block form-inline mr-2 mr-md-3 my-2 my-md-0 mw-100">
                        <div class="input-group">
                            <label class="sr-only" for="search">Search:</label>
                            <input type="text" class="form-control bg-light border-0 rounded-pill py-2 px-3"
                                   name="search"
                                   id="search-table" aria-label="Search" aria-describedby="basic-addon2"
                                   onkeyup="searchTablePlayer()">
                        </div>
                    </form>
                </div>
                <table class="table table-hover " id="player_table">
                    <thead class="table-dark">
                    <tr>
                        <th scope="col">Number</th>
                        <th scope="col">Name</th>
                        <th scope="col">Position</th>
                        <th scope="col">Season</th>
                        <th scope="col">Team</th>
                    </tr>
                    </thead>
                    <tbody class="table-group-divider">
                    {% for player in players %}
                        <tr style="cursor: pointer" onclick="window.location='{% url 'player_detail' player.id %}'">
                            <th scope="row">{{ player.number_player }}</th>
                            <td>{{ player.name }}</td>
                            <td>{{ player.position }}</td>
                            <td>
                                {% for player_team_season in player.playerteamseason_set.all %}
                                    {{ player_team_season.season.name }}{% if not forloop.last %}, {% endif %}
                                {% endfor %}
                            </td>
                            <td>
                                {% for player_team_season in player.playerteamseason_set.all %}
                                    {{ player_team_season.team.name }}{% if not forloop.last %}, {% endif %}
                                {% endfor %}
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>

                <div id="no-results-message" style="display: none; margin-top: 10px;">
                    No se encontraron registros coincidentes.
                </div>
            </div>
        </div>

    </div>



{% endblock %}
```

myapp/templates/new_player.html
{% extends 'base.html' %}
{% block content %}

    <h1>Agregar Jugador</h1>

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Guardar</button>
    </form>

{% endblock %}

myapp/templates/new_stadium.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    {{ form.media }}

    <style>
        #myMap {
            width: 100%; /* Utiliza el 100% del ancho disponible */
            height: 400px; /* Altura fija para mantener proporciones adecuadas */
            margin-top: 20px; /* Margen superior para separar del contenido anterior */
            border: 2px solid #ccc;
        }
    </style>

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-xl-8 col-lg-10 col-md-9">
                <div class="card o-hidden border-0 shadow-lg">
                    <div class="card-body p-5">
                        <div class="text-center">
                            <h1 class="h4 text-gray-900 mb-4">Nuevo Lugar</h1>
                        </div>
                        <form method="post" class="form-group mx-auto mt-2">
                            {% csrf_token %}

                            {{ error }}

                            {% if form.errors %}
                                <div class="alert alert-danger" role="alert">
                                    <strong>Error:</strong> There was a problem with the form submission.
                                </div>
                            {% endif %}

                            {{ form.as_p }}
                            <input type="hidden" id="geolocation" name="geolocation">
                            <div id="myMap"></div>
                            <div class="text-center">
                                <a class="btn btn-secondary rounded-pill btn-md w-25"
                                   href="{% url 'competition_detail' competition.id %}">Cancel</a>
                                <button type="submit" class="btn btn-primary rounded-pill btn-md w-25">Submit</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>



    <script type="text/javascript"
            src="https://www.bing.com/api/maps/mapcontrol?key=ApzrK8-qiiRRdCt-zCJCBU42D-OCpYnOW-Yu47cE30jPPlILtWr52Z_ySM0wErJA&callback=loadMapScenario"
            async defer></script>

    <script>
        function loadMapScenario() {
            map = new Microsoft.Maps.Map(document.getElementById('myMap'),
                {
                    credentials: 'ApzrK8-qiiRRdCt-zCJCBU42D-OCpYnOW-Yu47cE30jPPlILtWr52Z_ySM0wErJA'
                });

            Microsoft.Maps.Events.addHandler(map, 'click', function (e) {

                if (e.targetType == 'map') {

                    var point = new Microsoft.Maps.Point(e.getX(), e.getY());
                    var location = e.target.tryPixelToLocation(point);

                    var pushpin = new Microsoft.Maps.Pushpin(location, {
                        color: 'red'
                    });

                    map.entities.clear();
                    map.entities.push(pushpin);

                    // Actualiza el valor del campo geolocation con las coordenadas
                    document.getElementById('geolocation').value = location.latitude + ',' + location.longitude;
                }
            });
        }
    </script>


{% endblock %}
```

myapp/templates/players.html
{% extends 'base.html' %}

{% block content %}

    {% load static %}

    <head>
        <title>Listado de Jugadores</title>
    </head>

    <main>
        <h1>Listado de Jugadores</h1>

        <div class="d-flex justify-content-end">
            <form class="d-none d-sm-inline-block form-inline mr-2 mr-md-3 my-2 my-md-0 mw-100">
                <div class="input-group">
                    <label class="sr-only" for="search">Search:</label>
                    <input type="text" class="form-control bg-light border-0 rounded-pill py-2 px-3" name="search"
                           id="search-table" aria-label="Search" aria-describedby="basic-addon2"
                           onkeyup="searchTablePlayer()">
                </div>
            </form>
        </div>

        <table class="table table-hover " id="player_table">
            <thead class="table-dark">
            <tr>
                <th scope="col">Number</th>
                <th scope="col">Name</th>
                <th scope="col">Position</th>
                <th scope="col">Season</th>
                <th scope="col" colspan="2">Team</th>
            </tr>
            </thead>
            <tbody class="table-group-divider">
            {% for player in players %}
                <tr style="cursor: pointer" onclick="window.location='{% url 'player_detail' player.id %}'">
                    <th scope="row">{{ player.number_player }}</th>
                    <td>{{ player.name }}</td>
                    <td>{{ player.position }}</td>
                    <td>
                        {% for team in player.teams.all %}
                            {{ team.season.name }}{% if not forloop.last %}, {% endif %}
                        {% endfor %}
                    </td>
                    <td colspan="2">
                        {% for team in player.teams.all %}
                            {{ team.name }}{% if not forloop.last %}, {% endif %}
                        {% endfor %}
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

        <div id="no-results-message" style="display: none; margin-top: 10px;">
            No se encontraron registros coincidentes.
        </div>

    </main>




{% endblock %}
```